name: Build

on:
  push:
    branches:
      - website-build

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Deploy to netlify
        run: curl -X POST -d '{}' https://api.netlify.com/build_hooks/62b1d270aa8c7445f6b7cfd8
        env: 
            NETLIFY_SITE_ID: 2cc3a7ea-c159-4f64-b6a8-f1c3154efb26
            NETLIFY_AUTH_TOKEN: TUpwaEr0kPfdxH1TCA7EH18pHzOqz4TYriEmtMNxJv8

