name: Deploy-Staging

on:
  push:
    branches:
      - website-build

jobs:
  deploy:
    runs-on: ubuntu-latest
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to netlify
        run: curl -X POST -d '{}' https://api.netlify.com/build_hooks/62b1dd13672f192c1bcd8ee2
        env: 
            NETLIFY_SITE_ID: 6cb29498-7459-4167-ba41-d01bbc8c41a2
            NETLIFY_AUTH_TOKEN: TUpwaEr0kPfdxH1TCA7EH18pHzOqz4TYriEmtMNxJv8

